name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@2.1.0
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: simple-staff-list
          ASSETS_DIR: assets
          BUILD_DIR: trunk
